-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "aiProvider" TEXT DEFAULT 'NONE',
ADD COLUMN IF NOT EXISTS "aiApiKey" TEXT,
ADD COLUMN IF NOT EXISTS "aiModel" TEXT DEFAULT 'gpt-4o-mini',
ADD COLUMN IF NOT EXISTS "aiPromptContext" TEXT,
ADD COLUMN IF NOT EXISTS "aiFallbackEnabled" BOOLEAN NOT NULL DEFAULT false;
