-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "orderNumber" SERIAL NOT NULL,
ADD COLUMN IF NOT EXISTS "customerAddress" TEXT,
ADD COLUMN IF NOT EXISTS "driverName" TEXT,
ADD COLUMN IF NOT EXISTS "driverPhone" TEXT;
